[tool.poetry]
name = "snippets"
version = "0.1.0"
description = "Code snippets used on https://geniepy.com"
authors = ["Siddhant Goel <me@geniepy.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Authlib = "^1.2.1"
starlette = "^0.32.0"
strawberry-graphql = "^0.215.0"
uvicorn = "^0.24.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
